name: Deploy

on:
  push:
    branches: [master, test/cd]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Set AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: my_images
          MQTT_USER: ${{ secrets.USER }}
          MQTT_PASS: ${{ secrets.PASS }}
          IMAGE_TAG: scuffed_metar_image
        run: |
          aws ecr batch-delete-image --repository-name $ECR_REPOSITORY --image-ids imageTag=$IMAGE_TAG
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --build-arg WEBHOOK_URL_ARG=${{ secrets.WEBHOOK_URL }} -f main.Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update Container Image
        run: |
          curl -H "Authorization: Bearer ${{ secrets.BEARER }}" ${{ secrets.URL }}

